mysqldb:
    container_name: mysqldb
    image: tutum/mysql
    restart: always
    net: "host"
    environment:
        - MYSQL_USER=airflow
        - MYSQL_PASS=airflow
        - ON_CREATE_DB=airflow
        - HOST=

rabbitmq:
    container_name: rabbitmq
    image: puckel/docker-rabbitmq
    restart: always
    net: "host"
    environment:
        - RABBITMQ_USER=airflow
        - RABBITMQ_PASSWORD=airflow
        - RABBITMQ_VHOST=airflow
        - HOST=

webserver:
    container_name: webserver
    image: liligo/airflow-base
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - HOST=
    volumes:
        - /opt/airflow/dags:/usr/local/airflow/dags
    net: "host"
    command: webserver

flower:
    container_name: flower
    image: liligo/airflow-base
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - HOST=
    volumes:
        - /opt/airflow/dags:/usr/local/airflow/dags
    net: "host"
    command: flower

worker:
    container_name: worker
    image: liligo/airflow-worker
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - HOST=
    net: "host"
    volumes:
        - /opt/airflow/dags:/usr/local/airflow/dags
    command: worker

scheduler:
    container_name: scheduler
    image: liligo/airflow-base
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - HOST=
    net: "host"
    volumes:
        - /opt/airflow/dags:/usr/local/airflow/dags
    command: scheduler
